---
title: "Main simulation script"
author: "Lily Andrews"
date: "6/24/2021"
output: html_document
---
Simple Mendelian Randomisation
```{r download packages}
library(simulateGP)
library(systemfit)
```

```{r set parameters}
# Set causal effect of x on y
beta_xy <- -0.3
# Set number of instruments for x
nsnp <- 3
# Set number of individuals to simulate
nid <- 10000
# Set variance explained in x by the instruments
rsq_gx <- 0.05
# allele frequencies of 0.5
af=0.5
# effect sizes of u on x
ux_eff <- 0.3
# effect sizes of u on y
uy_eff <- 0.3
```

```{r running simulation}
source('../R/run_simulation.R')
set.seed(63958321)

sim<-list()
for (i in 1:100){
  sim[[i]]<-run_simulation(beta_xy,nsnp,nid,rsq_gx,af,ux_eff,uy_eff)
}
```

```{r results of simulation}
effects<-sapply(1:100,function(x)sim[[x]]$mr$coefficients[2])
summary(effects)
boxplot(effects)
```
Simple two-sample Mendelian Randomization 
```{r download packages}
library(simulateGP)
library(systemfit)
```

```{r generate summary level data from indivdual level data}
nid <- 10000
# Set number of instruments for x
nsnp <- 20
#minor allele frequency
maf <- 0.5
# Set variance explained in x by the instruments
rsq_gx <- 0.05
# Set variance in y
rsq_gy <- 0.1
```

```{r run 2 sample MR simulation}
source('../R/two_sample_mr_simulation.R')
set.seed(63958321)
two_sample_mr_simulation(nsnp,nid,rsq_gx,rsq_gy,maf)
```

